#ifndef _H_STB_VORBIS_WRAPPER_
#define _H_STB_VORBIS_WRAPPER_

#define STB_VORBIS_NO_CRT
#define STB_VORBIS_NO_STDIO
#define STB_VORBIS_NO_PUSHDATA_API

#define STB_VORBIS_HEADER_ONLY
#include "stb_vorbis.cpp"
#undef STB_VORBIS_HEADER_ONLY

#endif // !_H_STB_VORBIS_WRAPPER_

