#include "../Code/Libraries/base64.cpp"
#include "../Code/Libraries/gabor_json.cpp"
#include "../Code/Libraries/imgui.cpp"
#include "../Code/Libraries/imgui_draw.cpp"
#include "../Code/Libraries/imgui_neo_internal.cpp"
#include "../Code/Libraries/imgui_neo_sequencer.cpp"
#include "../Code/Libraries/imgui_stdlib.cpp"
#include "../Code/Libraries/imgui_tables.cpp"
#include "../Code/Libraries/imgui_widgets.cpp"
#include "../Code/Libraries/ImMath.cpp"

#include "../Code/main.cpp"
#include "../Code/Action.cpp"
#include "../Code/Application.cpp"
#include "../Code/Asset.cpp"
#include "../Code/AssetManager.cpp"
#include "../Code/Embedded.cpp"
#include "../Code/SceneNode.cpp"
#include "../Code/SpriteNode.cpp"
#include "../Code/Tools.cpp"
#include "../Code/Track.cpp"
#include "../Code/TransformNode.cpp"
#include "../Code/UndoManager.cpp"

#include "../Code/PlatformWasm.cpp"
#include "../Code/Libraries/stb_image.c"
#include "../Code/Libraries/sokol_impl.cpp"